baseURL: "https://Sreenivas.com/"
languageCode: en-us
title: Sreenivas R Angara
theme: PaperMod

params:
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories
      weight: 40

    - identifier: tags
      name: Tags
      url: /tags
      weight: 50

    - identifier: archives
      name: Archives
      url: /archives
      weight: 60
